name: OWASP ZAP Baseline Scan

on:
  push:
    branches:
      - main  

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://testphp.vulnweb.com/'  # Replace with your target URL


